version: "3.9"

services:

  php:
    image: php:8.5.4-apache
    container_name: mvc

    ports:
      - "8080:80"

    volumes:
      - ./src:/var/www/html

    working_dir: /var/www/html

    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql mysqli &&
      a2enmod rewrite &&
      sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf &&
      apache2-foreground
      "

  mysql:
    image: mysql:8.0
    container_name: mysql_mvc

    restart: no

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mvc

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: